services:
  - type: web
    name: groundwater-prediction
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn groundwater_prediction.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com
      - key: DEBUG
        value: false
    autoDeploy: true
